spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rsSystemForTest
    username: root
    password: liaowenqiang
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create